SUBMARINE-537. missing JacksonJsonProvider in uber jar
### What is this PR for?
submarine-spark-security fails with java.lang.NoClassDefFoundError

uber jar is missing submarine_spark_ranger_project/org/codehaus/jackson/jaxrs/JacksonJsonProvider

### What type of PR is it?
[Bug Fix]

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/SUBMARINE-537

### How should this be tested?

### Screenshots (if appropriate)

### Questions:
* Does the licenses files need update? Yes/No
* Is there breaking changes for older versions? Yes/No
* Does this needs documentation? Yes/No

Author: Gustavo Martin Morcuende <gu.martinm@gmail.com>

Closes #319 from gumartinm/SUBMARINE-537 and squashes the following commits:

b4ece74 [Gustavo Martin Morcuende] SUBMARINE-537. fixing org.codehaus.jackson:jackson-jaxrs version
277e149 [Gustavo Martin Morcuende] SUBMARINE-537. Including JacksonJsonProvider in uber jar